### PR TITLE
235 documentation

### PR DESCRIPTION
**Pull request by Floinko**

### CODE REVIEW

**Comment by krisutofu** [comment]
Okay, I need to do that user documentation Tuesday.

**Review by krisutofu — APPROVED** [review]
Please merge

**Comment by steinkohl** [comment]
@christoph-ehm Why did you merge that already? There was no second review. The Team creation part is still outdated.

**Comment by krisutofu** [comment]
> @christoph-ehm Why did you merge that already? There was no second review. The Team creation part is still outdated.

In that case, please issue a PR update. The deliverables deadline had been this day, so it had to be merged fast, since it was almost 8am. No code is involved anyways.

**Pull request merged**
