### PR TITLE
blackchain crawler cron job

### PR DESCRIPTION
**Pull request by steinkohl**
#149

### CODE REVIEW

**Comment by steinkohl** [comment]
Added "ABIs" Collection:
ABIs-Collection

Added "Drops" Collection:
Drops-Collection1
Drops-Collection2

**Comment by dominic-heil** [comment]
Don't forget to add a small readme :)

**Comment by steinkohl** [comment]
this cron job is already deployed on the mintme.tk backend and the results can be seen in the database

**Review by dominic-heil — APPROVED** [review]
LGTM! Works well on our servers

**Review by Floinko — APPROVED** [review]
LGTM!

**Pull request merged**
