### PR TITLE
Implemented changes regarding #94

### PR DESCRIPTION
**Pull request by steinkohl**
modified both templates regarding #94

### CODE REVIEW

**Comment by krisutofu** [comment]
Could you add some more text for the description? Is this PR linked to the story in the kanban board?

**Comment by krisutofu** [comment]
Is there additional effort required to directly identify and conditionally select frontend behavviour based on this user team?

**Review by krisutofu — COMMENTED** [review]
Hm, would it be okay, if I change the `frontend/areas/*` into one generic component which also includes the partners? Then it would be ready for use.

**Comment by krisutofu** [comment]
Could you rebase this PR-branch onto the latest 'main' branch? That would be reasonable before I try to add something to this PR.

**Comment by steinkohl** [comment]
This story only requires a backend implementation, so this PR can be fast forwarded quite well and don't has to be rebased.
And I also don't want to delete the branches until I'm sure, that there is nothing missing in the main branch.
But I will add some more text to the readme if you want

**Comment by steinkohl** [comment]
There is a second ticket for the frontend part -> #132

**Review by dominic-heil — APPROVED** [review]
LGTM

**Comment by krisutofu** [comment]
> There is a second ticket for the frontend part -> #132

Alles klar. Ich hätte zumindest schon eine Vorstellung, wie diese Story erfüllt wird.

**Review by krisutofu — APPROVED** [review]

**Pull request merged**
