### PR TITLE
Added first version of NFT drop banner

### PR DESCRIPTION
**Pull request by BerinikeTech**
Co-authored-by: Dominic heil <mail@d-heil.de>
Co-authored-by: Berinike Tech <berinike@delphai.com>

### CODE REVIEW

**Comment by dominic-heil** [comment]
Some images:

image

image

image

**Review by dominic-heil — APPROVED** [review]

**Comment by krisutofu** [comment]
Looks cool!
Seems like we still have PR review problems.
For frontend stuff you could usually add me but I'm honestly rather glad that this time I didn't need to bother so much with reviewing PRs. This React JavaScript stuff is streneous. I usually find a lot of readability and software engineering "problems" for myself but I just won't mind violations against our review guidelines anymore.

**Review by krisutofu — APPROVED** [review]

**Comment by krisutofu** [comment]
And I hope you used an image which is not copyrighted XD .

**Comment by krisutofu** [comment]
Ah well, you didn't include "reserved" and the "view" button (and the "retract" button what I expected however). What is the reason?

**Review by tuilagio — COMMENTED** [review]
LGTM. can't find the approve button

**Pull request merged**
