### PR TITLE
Added button to go to my collection

### PR DESCRIPTION
**Pull request by dominic-heil**
This PR adds a collection to quickly go to a users collection.
image

### CODE REVIEW

**Review by Floinko — APPROVED** [review]
LGTM

**Review by steinkohl — CHANGES_REQUESTED** [review]
I think this might need a update of the cypress test?

**Comment by tuilagio** [comment]
try pushing a dummies commit. The integration test sometimes can't find the UI component in time due to web page load.
If that is the case, this second attempt could complete the test in time.

**Review by steinkohl — APPROVED** [review]
LGTM

**Pull request merged**
