### PR TITLE
added creator to announcment; removed obsolete appwrite function

### PR DESCRIPTION
**Pull request by Floinko**

### CODE REVIEW

**Comment by tuilagio** [comment]
I would change `creator` to `author`.
Otherwise LGTM.

**Review by tuilagio — APPROVED** [review]

**Comment by krisutofu** [comment]
What does the failing test mean? Is it a timeout for a JavaScript promise?

**Comment by tuilagio** [comment]
Can you fix the conflict and github action error?

**Comment by tuilagio** [comment]
I encounter the same error occasionally. Properly the action run server has some load and therefore is the page loaded a bit slower. I see a lot of hard coded `await time` and this might be the root. Fix usually by `Re-run all test` in the action console

**Comment by JaPilgrim** [comment]
Looks good to me!

**Review by JaPilgrim — APPROVED** [review]
Looks good to me!

**Pull request merged**
