### PR TITLE
Split contracts to reduce size

### PR DESCRIPTION
**Pull request by JaPilgrim**
Nikes (now-merged) PR as base for branch

-Contract split up into
-Interface between them established
-Tested & verified´within remix
-However, verify & publish on etherscan does NOT work, as it somehow can't handle that the contract includes multiple contracts

### CODE REVIEW

**Review by BerinikeTech — CHANGES_REQUESTED** [review]
I can't approve this until it's deployed since we can't use the contract this way :/ If this kind of size reduction doesn't let us deploy the contract then we have to find another way to reduce the size that is compatible with the etherscan deployment.

**Comment by JaPilgrim** [comment]
Managed to verify & publish the contracts after all :)

NFTTHEWORLD: 0xFEe17E69fF1D884F4a8c4e32a493e8E4B1C3e331

TOKENFACTORY:
0x51AD1Bd7E70Ac9C9e6aD68023762DE860b0cD4DF

**Comment by BerinikeTech** [comment]
could you please add me to admins so I can test? :) 0x3c82B3B1128b8aead100671BBc7B6AD2E5cA2cD8

**Comment by JaPilgrim** [comment]
Done :) @BerinikeTech

**Review by BerinikeTech — APPROVED** [review]
Tested it on Etherscan, very nice :) Could you just add more documentation in the README if there are any things to remember when deploying? Like any specific fields to click, etc.

**Review by steinkohl — APPROVED** [review]
Code looks good and transaction artefacts in etherscan lookin fine.
LGTM

**Comment by krisutofu** [comment]
Could someone merge this PR, please? It is practically ready for the feature archive but not merged.

**Pull request merged**
